### ISSUE TITLE
Strange Warning in Angular: "Cannot find source file"

### ISSUE THREAD

**Issue by thorek** [vkolgi/json-to-graphql-query#26]
```
WARNING in ./node_modules/json-to-graphql-query/lib/types/EnumType.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/types/EnumType.ts': Error: Can't resolve '../../src/types/EnumType.ts' in '/Projects/activeql.d/activeql/angular/node_modules/json-to-graphql-query/lib/types'
```

Everything seems to work, I still like to figure out what's causes the warning, though. Any idea?

**Comment by thorek** [comment]
It's simply because the src folder is missing in your package. Can you include it?

**Comment by dupski** [comment]
I guess it'll just be a case of removing "src" from the npmignore file.

I'm not using a lot of node / typescript at the moment - does anyone know if it's common these days to include the original TS source along with the compiled versions in the NPM package? Seems a bit pointless if the definitions (d.ts) files are shipped, which is why this library currently doesn't...

**Comment by thorek** [comment]
Well, it does no harm. And file size shouldn’t be a problem in this case. So I suggest include it in the package. Otherwise the sourcemap should not point to src, since this results in the warning messages. 

Great job btw!

**Comment by thorek** [comment]
It would be really great if you either remove it from the sourcemap or include the src - otherwise there are always very annoying warning messages every time the application started. It would be really really appreciated.

**Comment by thorek** [comment]
👍
